=== victoraldecoa/WebServiceMatching/WSMatchMaking/src/Output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.kth.se/ict/id2208/Matching" 
        xmlns:tns="http://www.kth.se/ict/id2208/Matching" 
        elementFormDefault="qualified">
    <complexType name="MatchedElementType">
    	<sequence>
    		<element name="OutputElement" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="InputElement" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="Score" type="double" maxOccurs="1" minOccurs="1"/>
    	</sequence>
    </complexType>

    <complexType name="MatchedOperationType">
    	<sequence>
    		<element name="OutputOperationName" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="InputOperationName" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="OpScore" type="double" maxOccurs="1" minOccurs="1"/>
    		<element name="MacthedElement" type="tns:MatchedElementType" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>

    <complexType name="MatchedWebServiceType">
    	<sequence>
    		<element name="OutputServiceName" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="InputServiceName" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="MacthedOperation" type="tns:MatchedOperationType" maxOccurs="unbounded" minOccurs="1"/>
    		<element name="WsScore" type="double" maxOccurs="1" minOccurs="1"/>
    	</sequence>
    </complexType>
    
    <complexType name="WSMatchingType">
   		 <sequence>
    		<element name="Macthing" type="tns:MatchedWebServiceType" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>
    

    <element name="WSMatching" type="tns:WSMatchingType"/>
</schema>

=== victoraldecoa/WebServiceMatching/WSSemanticMatching/nnn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:WSMatching
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://www.kth.se/ict/id2208/Matching'
    xsi:schemaLocation='http://www.kth.se/ict/id2208/Matching src/Output.xsd'>
    <ns1:Macthing>
        <ns1:OutputServiceName></ns1:OutputServiceName>
        <ns1:InputServiceName></ns1:InputServiceName>
        <ns1:MacthedOperation>
            <ns1:OutputOperationName></ns1:OutputOperationName>
            <ns1:InputOperationName></ns1:InputOperationName>
            <ns1:OpScore></ns1:OpScore>
            <ns1:MacthedElement>
                <ns1:OutputElement></ns1:OutputElement>
                <ns1:InputElement></ns1:InputElement>
                <ns1:Score></ns1:Score>
            </ns1:MacthedElement>
        </ns1:MacthedOperation>
        <ns1:WsScore></ns1:WsScore>
    </ns1:Macthing>

</ns1:WSMatching>

=== victoraldecoa/WebServiceMatching/WSSemanticMatching/build/classes/Output_provided.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:WSMatching 
        xmlns:tns="http://www.kth.se/ict/id2208/Matching" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://www.kth.se/ict/id2208/Matching Output.xsd ">
    <tns:Macthing>
        <tns:OutputServiceName>WS_A</tns:OutputServiceName>
        <tns:InputServiceName>WS_B</tns:InputServiceName>
        <tns:MacthedOperation>
            <tns:OutputOperationName>getDrink</tns:OutputOperationName>
            <tns:InputOperationName>getWine</tns:InputOperationName>
            <tns:OpScore>0.9375</tns:OpScore>
            <tns:MacthedElement>
                <tns:OutputElement>Country</tns:OutputElement>
                <tns:InputElement>Country</tns:InputElement>
                <tns:Score>1.0</tns:Score>
            </tns:MacthedElement>
            <tns:MacthedElement>
                <tns:OutputElement>Price</tns:OutputElement>
                <tns:InputElement>Cost</tns:InputElement>
                <tns:Score>0.9</tns:Score>
            </tns:MacthedElement>
            <tns:MacthedElement>
                <tns:OutputElement>Region</tns:OutputElement>
                <tns:InputElement>Area</tns:InputElement>
                <tns:Score>0.85</tns:Score>
            </tns:MacthedElement>
            <tns:MacthedElement>
                <tns:OutputElement>Color</tns:OutputElement>
                <tns:InputElement>Colour</tns:InputElement>
                <tns:Score>1.0</tns:Score>
            </tns:MacthedElement>
        </tns:MacthedOperation>
        <tns:WsScore>0.9375</tns:WsScore>
    </tns:Macthing>
</tns:WSMatching>
